services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/"]
      interval: 30s
      timeout: 3s
      retries: 3
